# cluster.id and env, slacktoken, githubtoken are set via command-line flags.
# only static settings reside in this file

cluster:
  github:
    # webhook is automatically registered to this org
    organization: yourorgname
    # desired cluser state stored in your github repo
    repository: "yourorgname:yourreponame"
    # the github user used for git-clone and slack notifications
    machineuser: "yourgithubbot"
    slackuser: "yourslackbot"

# each service should have a set of config files
# used by herder to create per-microservice brigade-project
services:
  your-svc-x:
    brigade:
      config: brig-project-tmpl-1
  your-svc-y:
    brigade:
      config: brig-project-tmpl-2
  your-svc-z:
    # inherit defaults
